# Matrix Mathematics for Artificial Neural Networks (ANN)

## Project Overview
This notebook demonstrates the fundamental matrix mathematics used in Artificial Neural Networks (ANN). Matrix operations are the backbone of neural network computations, enabling efficient forward propagation, backpropagation, and weight updates.

## Objectives
- Understand matrix representation in ANN.
- Learn matrix multiplication and addition.
- Explore vectorized computations.
- Build a foundation for deep learning.

## Technologies Used
- Python
- NumPy
- Jupyter Notebook


### Import Libraries
This cell imports the required Python libraries for performing numerical and matrix operations.

In [ ]:
import numpy as np

### Create Matrices
This cell creates matrices/vectors that will be used to demonstrate mathematical operations.

In [ ]:
revenue = np.array([[180,200,220],[24,36,40],[12,18,20]])
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])

### Code Explanation
This code performs an important step in matrix mathematics for neural networks.

In [ ]:
profit = revenue - expenses
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

### Create Matrices
This cell creates matrices/vectors that will be used to demonstrate mathematical operations.

In [ ]:
price_per_unit = np.array([1000,400,1200])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])

### Code Explanation
This code performs an important step in matrix mathematics for neural networks.

In [ ]:
price_per_unit*units

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

### Matrix Multiplication
This cell performs matrix multiplication, the core operation used during forward propagation in neural networks.

In [ ]:
np.dot(price_per_unit,units)

array([34400, 50000, 64400])

### Code Explanation
This code performs an important step in matrix mathematics for neural networks.

## Conclusion

This project demonstrates how matrix mathematics forms the foundation of Artificial Neural Networks. Understanding these operations helps explain how neural networks efficiently process data and learn from examples using vectorized computations.